### ISSUE TITLE
hardware schematic

### ISSUE THREAD

**Issue by S0c5** [ipaq3115/PiWatch#1]
Hi guys, i love your work !!!! i understand the hardest that could be make your hardware, i want to know more about the hardware schematic, what voltage regulator your use for setup the LCD tft and if your use your own lcd library, 

can you make your project open hardware?

**Comment by ipaq3115** [comment]
I have some basic wiring setup on the LCD screen as seen here. 

![1 38_round_lcd](https://cloud.githubusercontent.com/assets/8430611/11999279/8990c9d4-aa88-11e5-9415-a7ee8327f312.jpg)

Look for PiScreen.h and PiScreen.cpp in this repository for the lcd library.

Not sure how much effort we are going to put into organizing this old info right now, we never really finalized any of it.
